course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2014-09-25
    end: 2014-12-10
    times: Tues & Thurs 6:30PM - 7:45PM
    course: 4085.582.01
    location: Orange Hall (ORN)-1380

instructor:
    name: Remy DeCausemaker
    email: remydcsi@rit.edu
    irc: decause
    avatar: http://www.libravatar.org/user/5d9d0a14af042b2f7877ab58de9b7702ca29bb9d34155dc58eff4ff6509d562c.png
    openhub: decause
    coderwall: decause
    twitter: Remy_D
    office:
        location: The MAGIC Center - SIH 1680
        hours: Monday, Wednesday, 4:00-5:00pm
    links:
        blog: http://foss.rit.edu/blog/decause
        linkedin: http://linkedin.com/in/decause
        github: http://github.com/decause
        opensource: http://opensource.com/users/remyd

assistant:
    name: Thunderdome
    email: Thunderdome@foss.rit.edu
    irc: Thunderdome
